### ISSUE TITLE
nsml error in baseline code

### ISSUE THREAD

**Issue by as12088** [Naver-AI-Hackathon/cs492I#16]
**Baseline code(https://github.com/GitGyun/CS492H_NSML_Project1_Baselline) error after nsml was recently updated. How do I solve it?**

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
NSML Log start!
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pytorch_metric_learning/utils/stat_utils.py", line 5, in <module>
    import faiss
ImportError: No module named 'faiss'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 31, in <module>
    from pytorch_metric_learning import miners
  File "/usr/local/lib/python3.5/dist-packages/pytorch_metric_learning/miners/__init__.py", line 1, in <module>
    from .base_miner import BaseMiner, BaseTupleMiner, BaseSubsetBatchMiner
  File "/usr/local/lib/python3.5/dist-packages/pytorch_metric_learning/miners/base_miner.py", line 4, in <module>
    from ..utils import common_functions as c_f
  File "/usr/local/lib/python3.5/dist-packages/pytorch_metric_learning/utils/__init__.py", line 1, in <module>
    from .accuracy_calculator import AccuracyCalculator
  File "/usr/local/lib/python3.5/dist-packages/pytorch_metric_learning/utils/accuracy_calculator.py", line 5, in <module>
    from . import stat_utils
  File "/usr/local/lib/python3.5/dist-packages/pytorch_metric_learning/utils/stat_utils.py", line 6, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
User session exited

**Comment by nkwook** [comment]
u can handle that error by commenting code related to pytorch_metric_learning.
