### ISSUE TITLE
kaist_14/korquad-open-ldbd/22 submission error

### ISSUE THREAD

**Issue by as12088** [Naver-AI-Hackathon/cs492I#37]
Traceback (most recent call last):
  File "run_squad.py", line 78, in <module>
    (),
  File "run_squad.py", line 77, in <genexpr>
    (tuple(conf.pretrained_config_archive_map.keys()) for conf in (BertConfig, RobertaConfig, XLNetConfig, XLMConfig)),
AttributeError: type object 'BertConfig' has no attribute 'pretrained_config_archive_map'
User session exited
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

I trained the baseline model and tried to submit in about 10 days ago. At that time, the docker image was not created, so submission was impossible due to a server problem. After the server problem was solved, I tried to submit again, but now it is said that it is impossible to submit due to a code problem. I don't understand, when I run the baseline code, why can't I just test after 4 days of learning? Please resolve it as soon as possible

**Comment by nsml-admin** [comment]
Please refer to this https://github.com/Naver-AI-Hackathon/cs492h/issues/34#issuecomment-643721935

**Comment by as12088** [comment]
I tried it but still getting problem. kaist_14/korquad-open-ldbd/25

**Comment by as12088** [comment]
same problem when I run the code. kaist_14/korquad-open-ldbd/26
It is totally unfair. I did same just things in 10 days ago. At that time, the code worked fine. I can't understand that I am getting an error when I try to run the code now. Where are all the attempts I have made?

**Comment by nsml-admin** [comment]
As I said in the [comment](https://github.com/Naver-AI-Hackathon/cs492h/issues/34#issuecomment-643721935), as the server is updated, new package versions are downloaded, but the package version has been updated in the meantime, and the updated package and code are not compatible.

To fix this error, please change setup.py like below

from
```python
# nsml: nsml/ml:cuda10.1-cudnn7-pytorch1.3keras2.3

from distutils.core import setup

setup(
    name='kaist-korquad-test',
    version='1.0',
    install_requires=[
        'boto3', 'regex', 'sacremoses', 'filelock', 'tokenizers',
        'tqdm', 'konlpy', 'sentencepiece', 'dataclasses', 'transformers'
    ]
)
```

to

```python
# nsml: nsml/ml:cuda10.1-cudnn7-pytorch1.3keras2.3

from distutils.core import setup

setup(
    name='kaist-korquad-test',
    version='1.0',
    install_requires=[
        'boto3', 'regex', 'sacremoses', 'filelock', 'tokenizers',
        'tqdm', 'konlpy', 'sentencepiece', 'dataclasses', 'transformers==2.10.0'
    ]
)

```

**Comment by as12088** [comment]
Are you saying that I can't test the model I've learned before, and I need to learn new ones after changing setup.py?

**Comment by as12088** [comment]
I fixed but it does not work!!

from distutils.core import setup

setup(
    name='kaist-korquad-test',
    version='1.0',
    install_requires=[
        'boto3', 'regex', 'sacremoses', 'filelock', 'tokenizers',
        'tqdm', 'konlpy', 'sentencepiece', 'dataclasses', 'transformers==2.10.0'
    ]
)

**Comment by nsml-admin** [comment]
Does test mean submit?

If you want to submit a previous session, please let us know your session name. We'll fix it and let you know again.

And if you have a session that doesn't work even though you changed it, please tell us sessionName

**Comment by as12088** [comment]
I want to submit kaist_14/korquad-open-ldbd/1

**Comment by nsml-admin** [comment]
Please submit again.
